x-enviromments: &x-enviromments
  - AMQP_URL: "amqp://guest:guest@lavinmq:5672/"
  - PREFETCH_COUNT: "0"
  - SHARD_COUNT: "1"
  - PROCESSOR_URL: "http://payment-processor-default:8080"
  - FALLBACK_URL: "http://payment-processor-fallback:8080"
  - DISABLE_LOG: "true"
  - remove: "me"

version: '3.4'
services:
  app1: &app
    image: docker.io/lukas8219/rinha-de-backend-2025-app:main-a52e7a23e-1753551398
    user: "1001:1001"
    build:
      context: .
      target: app
    hostname: app1
    restart: unless-stopped
    ipc: host
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app1.sock"
    networks:
      - backend
      - payment-processor
    expose:
      - "3000"
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '40MB'
  app2:
    <<: *app
    user: "1001:1001"
    ipc: host
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app2.sock"
    hostname: app2
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started

  consumer: &consumer
    <<: *app
    user: "1001:1001"
    hostname: "1"
    ipc: host
    cpuset: "0"
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/1.sock"
    cpu_shares: 3072
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '150MB'
        reservations:
          cpus: '1'
          memory: '150MB'
    image: docker.io/lukas8219/rinha-de-backend-2025-worker:main-a52e7a23e-1753551398
    build:
      context: .
      target: worker
    depends_on:
      lavinmq:
        condition: service_healthy

  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    healthcheck:
      test: ["CMD", "lavinmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'
        reservations:
          cpus: '0.1'
          memory: '35MB'
  pingora: # Pingora Load Balancer
    image: docker.io/lukas8219/rinha-de-backend-2025-load-balancer-pingora:pingora-0b7f83e5a-1753557406
    build:
      context: .
      dockerfile: Dockerfile.pingora
    user: "1001:1001"
    ipc: host
    environment:
      PORT: "9999"
    depends_on:
      - app1
      - app2
      - lavinmq
      - consumer
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    cpu_shares: 2048
    cpuset: "2"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '55MB'
        reservations:
          cpus: '0.1'
          memory: '55MB'
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
