x-enviromments: &x-enviromments
  - SQLITE_PATH: "/dev/shm/database.sqlite3?sync=off&journal_mode=WAL&busy_timeout=1000&cache_size=100000"
  - AMQP_URL: "amqp://guest:guest@lavinmq:5672/"
  - BATCH_INTERVAL: "50"
  - PREFETCH_COUNT: "0"
  - SHARD_COUNT: "1"
  - SKIP_DELAY: "true"
  - PROCESSOR_URL: "http://payment-processor-default:8080"
  - FALLBACK_URL: "http://payment-processor-fallback:8080"
  - DISABLE_LOG: "true"

version: '3.4'
services:
  app1: &app
    # image: lukas8219/rinha-be-2023-q3:latest
    build:
      context: .
      target: app
    hostname: app1
    privileged: true
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app1.sock"
    networks:
      - backend
      - payment-processor
    expose:
      - "3000"
    ipc: host
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '50MB'
  app2:
    <<: *app
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app2.sock"
    hostname: app2
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started

  consumer: &consumer
    <<: *app
    hostname: "1"
    cpu_shares: 3072
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '150MB'
        reservations:
          cpus: '0.01'
          memory: '150MB'
    build:
      context: .
      target: worker
    depends_on:
      lavinmq:
        condition: service_healthy

  cleanup:
    image: alpine:latest
    command: ["/bin/sh", "-c", "rm -rf /dev/shm/*"]
    ipc: host
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: '10MB'
        reservations:
          cpus: '0.01'
          memory: '10MB'
    restart: "no"
    networks:
      - backend

  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    healthcheck:
      test: ["CMD", "lavinmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    depends_on:
      - cleanup
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'
        reservations:
          cpus: '0.01'
          memory: '35MB'

  nginx: # Load Balancer
    ipc: host
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - lavinmq
      - consumer
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    cpu_shares: 2048
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'
        reservations:
          cpus: '0.01'
          memory: '35MB'
  
  warmup:
    image: curlimages/curl:latest
    entrypoint: ["/bin/sh", "-c"]
    command: |
      curl --fail --max-time 5 http://nginx:9999/payments-summary || true
    depends_on:
      - nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true