version: '3.4'
services:
  app1: &app
    # image: lukas8219/rinha-be-2023-q3:latest
    build: .
    hostname: app1
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./profiling-data:/app/profiling-data
    environment:
      PROCESSOR_URL: "http://payment-processor-default:8080"
      FALLBACK_URL: "http://payment-processor-fallback:8080"
      CIRCUIT_BREAKER_THRESHOLD: "5"
      CIRCUIT_BREAKER_TIMEWINDOW: "15"
      CIRCUIT_BREAKER_REENABLE_AFTER: "5"
      DISABLE_LOG: "true"
      SQLITE_PATH: "/dev/shm/database.sqlite3?sync=off&journal_mode=WAL&busy_timeout=1000"
      AMQP_URL: "amqp://guest:guest@lavinmq:5672/"
      BATCH_INTERVAL: "5"
    networks:
      - backend
      - payment-processor
    expose:
      - "3000"
    depends_on:
      lavinmq:
        condition: service_healthy
    ipc: host
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '20MB'
  app2:
    <<: *app
    hostname: app2

  consumer:
    <<: *app
    hostname: consumer
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '15MB'
    build:
      context: .
      dockerfile: Dockerfile.consumer
  consumer2:
    <<: *app
    hostname: consumer2
    build:
      context: .
      dockerfile: Dockerfile.consumer

  consumer3:
    <<: *app
    build:
      context: .
      dockerfile: Dockerfile.consumer
  consumer4:
    <<: *app
    build:
      context: .
      dockerfile: Dockerfile.consumer

  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    healthcheck:
      test: ["CMD", "lavinmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true