x-enviromments: &x-enviromments
  - SQLITE_PATH: "/dev/shm/database.sqlite3?sync=off&journal_mode=WAL&busy_timeout=1000&cache_size=100000"
  - AMQP_URL: "amqp://guest:guest@lavinmq:5672/"
  - BATCH_INTERVAL: "50"
  - PREFETCH_COUNT: "0"
  - SHARD_COUNT: "5"
  - SKIP_DELAY: "true"
  - PROCESSOR_URL: "http://payment-processor-default:8080"
  - FALLBACK_URL: "http://payment-processor-fallback:8080"
  - DISABLE_LOG: "true"

version: '3.4'
services:
  app1: &app
    # image: lukas8219/rinha-be-2023-q3:latest
    build:
      context: .
      target: app
    hostname: app1
    privileged: true
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app1.sock"
    networks:
      - backend
      - payment-processor
    expose:
      - "3000"
    depends_on:
      lavinmq:
        condition: service_healthy
    ipc: host
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '30MB'
  app2:
    <<: *app
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app2.sock"
    hostname: app2
  app3:
    <<: *app
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app3.sock"
    hostname: app3

  consumer: &consumer
    <<: *app
    hostname: "1"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '35MB'
    build:
      context: .
      target: worker
  consumer2:
    <<: *consumer
    hostname: "2"
  consumer3:
    <<: *consumer
    hostname: "3"
  consumer4:
    <<: *consumer
    hostname: "4"
  consumer5:
    <<: *consumer
    hostname: "5"

  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    healthcheck:
      test: ["CMD", "lavinmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'

  nginx: # Load Balancer
    ipc: host
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - lavinmq
      - consumer
      - consumer2
      - consumer3
      - consumer4
      - consumer5
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '25MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true