x-enviromments: &x-enviromments
  - AMQP_URL: "amqp://guest:guest@lavinmq:5672/"
  - PREFETCH_COUNT: "0"
  - SHARD_COUNT: "1"
  - PROCESSOR_URL: "http://payment-processor-default:8080"
  - FALLBACK_URL: "http://payment-processor-fallback:8080"
  - DISABLE_LOG: "true"
  - PORT: "9999"
  # - USE_HTTP: "true"

services:
  app1: &app
    image: docker.io/lukas8219/rinha-de-backend-2025-app:main-a52e7a23e-1753551398
    user: "1001:1001"
    build:
      context: .
      target: app
    hostname: app1
    restart: unless-stopped
    cpu_shares: 2048
    cpuset: "0"
    ipc: host
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app1.sock"
    networks:
      - backend
      - payment-processor
    expose:
      - "3001:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '125MB'
  app2:
    <<: *app
    user: "1001:1001"
    cpu_shares: 2048
    cpuset: "1"
    ipc: host
    ports:
      - "3002:9999"
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app2.sock"
    hostname: app2

  pingora: # Pingora Load Balancer
    image: docker.io/lukas8219/rinha-de-backend-2025-load-balancer-pingora:pingora-0b7f83e5a-1753557406
    build:
      context: .
      dockerfile: Dockerfile.pingora
      cache_from:
         - docker.io/lukas8219/rinha-de-backend-2025-load-balancer-pingora:latest
    user: "1001:1001"
    ipc: host
    security_opt:
      - seccomp=unconfined
    environment:
      PORT: "9999"
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    cpu_shares: 2048
    cpuset: "2"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '55MB'
        reservations:
          cpus: '0.3'
          memory: '55MB'

  # nginx:
  #   image: nginx:latest
  #   user: "1001:1001"
  #   ipc: host
  #   networks:
  #     - backend
  #   ports:
  #     - "9999:9999"
  #   volumes:
  #     - nginx_cache:/var/cache/nginx
  #     - nginx_log:/var/log/nginx
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   cpu_shares: 1024
  #   cpuset: "3"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: '55MB'
  #       reservations:
  #         cpus: '0.1'
  #         memory: '55MB'

volumes:
  nginx_cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001"
  nginx_log:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1001,gid=1001"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
